#import "@preview/acrostiche:0.7.0": acr
#import "/template/_helpers.typ": hint, todo

= Ausblick <outlook>

== Fazit
Die Zielsetzung der Arbeit wurde laut Aussagen des Praxispartners mehr als erfüllt, wie beim zweiten Interview (@second_interview_gks) bestätigt wurde. Das primäre Ziel lag darin, Fachpersonen bei der Qualitätsprüfung von #acr("IFC")-Modellen nach #acr("eBKP-H") unterstützen zu können. Das Modell ist bereits fähig, vier wichtige Labels für eine solche Zuweisung korrekt vorherzusagen. Des Weiteren ist der Entscheid für die Vorhersage der Labels anstelle einer direkten Klassifikation der richtige, da so den Fachpersonen die Anomalien direkt gruppiert und aufgezeigt werden können. In Zukunft, sobald alle Labels vorhergesagt werden können, wäre eine direkte Zuweisung nach #acr("eBKP-H") möglich, indem die Zuweisungsmatrix der #link("https://www.idc.ch")[IDC AG] verwendet werden kann. Aktuell bleibt dies jedoch noch ein offener Punkt.

Die erste Hypothese ist teilweise erfüllt. Die drei Labels "#acr("IFC")-Entität", "Lage" und "Tragend" erfüllen die Macro-F1-Werte der Hypothesen. Beim Label "vordefinierter Typ" wird die Hypothese widerlegt, jedoch konnte beim zweiten Interview (@second_interview_gks) die Grundproblematik identifiziert werden, welche sich mit der @confusion_matrix_predefined_type_testset deckt. Viele Elemente werden bei "vordefinierter Typ" korrekt präzisiert, jedoch mehr als effektiv benötigt. Dies ist für eine Fachperson der Bauökonomie zu vernachlässigen und für weitere Analysen sogar von Vorteil. Lediglich einzelne Elemente weisen eine falsche Vorhersage auf. Diese wurden gemeinsam mit Patrick Muff anhand der Fehleranalyse mit der Demo beim Projekt "LUMU" herauskristallisiert. Dadurch ist der Wert für die Praxis besser, als er mit dem Macro-F1-Wert abgebildet ist. Bei der zweiten Hypothese wurde bestätigt, dass gradientenbasierte Modelle wie #acr("XGBoost") vergleichbare Resultate wie #acr("RF") erzielen können. Spannenderweise ist bei diesem Projekt die Trainingszeit beim Modell #acr("XGBoost") länger als beim #acr("RF"). Diese Tatsache widerspricht der konsultierten Literatur. Des Weiteren wurde im zweiten Interview auch erkannt, dass nicht bei allen Bauelementen die Informationen korrekt hinterlegt waren. Trotz dieser Fehler in der Ground-Truth konnte das finale Modell viele wichtige Muster lernen, um eine gute Performance abzubilden. Bei einem qualitativeren Datenset und mit mehr Daten wäre die Performance der Modelle noch besser gewesen.

Insgesamt ist es ein erfolgreiches Projekt, welches in Zukunft bei der #link("https://www.gks.ch")[GKS Architekten AG] in der Praxis bei einer monatlichen Modellprüfung (PreCheck) eingesetzt wird. Es bedarf lediglich einer Erweiterung um eine Feedbackschlaufe für das Ignorieren gleicher Elemente, welche bereits als Fehlklassifikation vom Modell von Fachpersonen erkannt worden sind. Dies, da die Prüfung nicht einmalig, sondern monatlich gemacht werden soll.

== Limitierungen
Beim vorliegenden Projekt wurden von der #link("https://www.gks.ch")[GKS Architekten AG] 13 Projekte für die Datenerhebung zur Verfügung gestellt. Alle diese Projekte wurden mit der nativen Software ArchiCAD erstellt. Dadurch ergibt sich die Limitierung auf nur ein vorhandenes Architekturbüro und den Export der Modelle aus einer Software. Es gibt keine Tests auf weiteren Modellen wie Revit, Vectorworks, Blender oder Rhino. Von den 13 relevanten Labels bzw. 21 Eigenschaften gemäss der Zuweisungsmatrix der #link("https://www.idc.ch")[IDC AG], welche für eine vollumfängliche Zuweisung benötigt werden, sind nur vier Labels verwendet worden, da für die anderen Labels zu wenige Daten vorhanden waren. Zudem besteht ein kleines Risiko für ein Datenleck, da ähnliche Featurevektoren aus verschiedenen Projekten in den jeweiligen Validation- und Testsplits vorhanden sein können.

== Diskussion

=== Stärken des geometriebasierten Ansatzes
Der auf Geometrie basierte Ansatz hat eine grosse Stärke gegenüber anderen Methoden, da bei einem #acr("IFC")-Export kein Informationsverlust stattfindet, die Geometrie bleibt immer erhalten. Daraus resultiert auch keine Abhängigkeit zu manuell gepflegten Properties wie der Lage, Tragend oder ähnlichen. Einzige Schwäche des Ansatzes ist der selbst gewählte Weg, die Materialien aus der Geometrie zu lesen. Zu Beginn der Projektphasen sind die Materialien der Bauteile nicht immer bekannt und dies kann deshalb zu Fehlern führen. Jedoch müssen die Materialien für die Kostenschätzung immer bekannt sein, da dort bereits auf Basis der Bauelemente die Schätzung gemacht wird. Somit stellt sich ein kleines Restrisiko dieses Ansatzes. Zudem werden die Materialien aus den Geometrien ausgelesen, welche die Fachpersonen benötigen, um Grundrisse, Schnitte und Detailstudien aus den 3D-Modellen zu generieren. Dadurch wären bei einem falschen Material auch die jeweiligen Pläne falsch, was bei den regelmässigen Kontrollen der Pläne ein kleines Risiko darstellt. Der Ansatz ist zudem einfach, ohne neue Labels, auf andere Projekte adaptierbar, da nur geometrische Eigenschaften der Bauelemente extrahiert werden. Zudem sind die Anomalieanalysen einfach in die bestehenden #acr("BIM")-Workflows via der #acr("BCF")-Schnittstelle integrierbar.

=== Vergleich mit den bestehenden Literaturen
Ein direkter Vergleich der Literaturen ist nicht möglich, da die vorliegende Arbeit die Klassifikation wichtiger Labels für ein #acr("eBKP-H")-Mapping anstrebt. Zudem bewerten die meisten Literaturen die Resultate mit deren Accuracies, während in dieser Arbeit die Performance primär über Macro-F1 und #acr("MCC") gemessen wird. Des Weiteren haben viele Studien die Aufteilungen elementweise und nicht pro Projekt gemacht, was häufig zu einem Datenleck führen kann und dadurch die sehr guten Resultate der Studien bekräftigt. Auch wurde nicht immer ein Testset mit ungesehenen Daten erstellt, wie bereits im @challenges aufgezeigt wurde.

Es gibt jedoch Parallelen zur Arbeit. Das finale Modell erzielt über alle Labels einen Macro-F1-Wert von 0,7368 und eine Accuracy von 82,71 %. Einzelne Labels wie "#acr("IFC")-Entität" oder "isExternal" erreichen eine Accuracy von 92,56 % und 84,73 %. Das sind bereits sehr gute Ergebnisse, welche durch einen Confidence-Schwellwert weitere Performancegewinne erzielen. "#acr("IFC")-Entität" erhöht sich dadurch auf eine Accuracy von 99,26 % und "isExternal" liegt neu bei 93,92 %. Diese Resultate liegen im mittleren Bereich der erzielten Accuracy-Werte der Literaturen für #acr("RF") @austern_incorporating_2024 @utkucu_classification_2024 @xu_automatic_2022 @tang_automatic_2025, welche zwischen 75,9 % und 100,0 % erzielt haben. Das finale Ensemble-Modell liegt zudem unter den erzielten Werten der Studie von #cite(<li_ensemble-learning-based_2022>, form: "prose"), worin sie eine Accuracy von 95,0 % und einen F1-Wert von 97,0 % mit einem #acr("XGBoost")-Modell erzielt haben.

Die Schwäche der horizontalen Elemente bestätigt sich zudem durch die Studie von #cite(<koo_using_2019>, form: "prose"). Auch sie hatten oft "IfcSlab" als Wand fehlklassifiziert. Zudem wurden bei einer Studie Fenster als Sanitärobjekte erkannt @austern_incorporating_2024. In dieser Arbeit wurden Sanitärobjekte beispielsweise mit Wänden vertauscht. Somit decken sich diese Probleme mit den Problemen der Literaturen. Des Weiteren fällt auf, dass bei kleineren Datensätzen, einem echten Holdout und hoher Varianz die Accuracy-Werte auf 81,0 bis 90,0 % fallen @austern_incorporating_2024, was auch in der vorliegenden Arbeit der Fall ist.
#pagebreak()

== Ausblick
Die vorliegende Arbeit bildet ein wichtiges Fundament in einer #acr("ML")- und #acr("KI")-gestützten Qualitätsprüfung bei #acr("IFC")-Dateien. Weitere offene Punkte für zukünftige Arbeiten sind beispielsweise bei einem grösseren Datensatz das Training der weiteren 9 von 13 Labels für eine vollumfängliche Prüfung aller Labels für das Mapping nach #acr("eBKP-H"). Die Hyperparameter-Optimierung könnte zudem produktiv in einer Trainingspipeline eingesetzt werden, da sie momentan lediglich explorativer Natur ist. Als weitere Folgearbeit wäre die Untersuchung von #acr("MVCNN") oder #acr("DL") (PointNet, #acr("GNN")) bei grösseren Datensätzen von Relevanz.

Aktuell wurden die Ergebnisse der selektierte Fehlergruppen einer Fachperson im Baumanagement-Sektor präsentiert, gemeinsam besprochen und analysiert. Eine weitere Qualitätsprüfung der Resultate wäre eine quantitative Umfrage der Missklassifikationen zwischen Fachpersonen und fachfremden Personen. Dabei wäre die spannende Frage, ob fachfremde oder fachkundige Personen überhaupt in der Lage sind, nur auf Basis geometrischer Eigenschaften die korrekten Klassen zu identifizieren. Das vorgeschlagene Ensemble-Modell mit den #acr("MLP")-, #acr("RF")- und #acr("XGBoost")-Modellen ist ein spannender Schritt, jedoch könnten dort andere Modellkombinationen weiter analysiert und vertieft werden. Als weiterer Punkt wurde in der vorliegenden Arbeit das Thema der Erklärbarkeit der Modelle angeschnitten. Dies wäre ein eigenständiges Thema der jeweiligen Modelle, wobei bei den #acr("ML")-Modellen die Erklärbarkeit einfacher studiert werden kann. Bei einem #acr("MLP") ist die Erklärbarkeit anspruchsvoller aufgrund der Konnektivität der Netzwerke, jedoch können die aktivierten Neuronen bei den jeweiligen Bauelementen studiert und analysiert werden.
