#import "@preview/acrostiche:0.7.0": init-acronyms

#init-acronyms((
  "AABB": "Achsenausgerichtete Begrenzungsboxen",
  "AdaBoost": "Adaptive Boosting",
  "ANFIS": "Adaptive Neuro Fuzzy Inference System",
  "BCF": "Building collaboration Format",
  "BIM": "Building Information Modeling",
  "BRep": "Boundary Representation",
  "CAD": "Computer-Aided Design",
  "CatBoost": "Categorical Boosting",
  "CBS": "Cost Breakdown Structure",
  "CDE": "Common Data Environment",
  "CNN": "Convolutional Neural Network",
  "CSG": "Constructive Solid Geometry",
  "CSV": "Comma-Separated Values",
  "DGCNN": "Dynamic Graph CNN",
  "DNN": "Deep Neural Network",
  "DL": "Deep Learning",
  "DT": "Decision Tree",
  "ET": "Extra Trees",
  "JSON": "JavaScript Object Notation",
  "GBDT": "Gradient Boosted Decision Trees",
  "EdgeConv": "Edge Convolution",
  "EL": "Ensemble Learning",
  "eBKP-H": "Erweiterter Baukostenplan nach Hochbau",
  "EM": "Ensemble Modell",
  "ExtraTree": "Extremely Randomized Trees",
  "GAT": "Graph Attention Networks",
  "GA-GBR": "Genetisch optimiertes Gradient Boosting Regression",
  "GUID": "Globally Unique Identifier",
  "GNN": "Graph Neural Networks",
  "GCN": "Graph Convolutional Networks",
  "HSLU": "Hochschule Luzern",
  "IFC": "Industry Foundation Classes",
  "IQR": "Interquartilsabstand",
  "ISO": "Internationale Organisation für Normung",
  "KI": "Künstliche Intelligenz",
  "KNN": "K-Nearest Neighbors",
  "LightGBM": "Light Gradient Boosting Machine",
  "LoD": "Level of Detail",
  "LoG": "Level of Geometry",
  "ML": "Machine Learning",
  "MCC": "Matthews Correlation Coefficient",
  "MLP": "Multilayer Perceptron",
  "MVCNN": "Multi-View Convolutional Neural Network",
  "NaN": "Not a Number",
  "NBI": "National Bridge Inventory",
  "NN": "Neurales Netzwerk",
  "PCA": "Principal Component Analysis",
  "Psets": "Property sets",
  "QS": "Qualitätssicherung",
  "QTO": "Quantity Take-Off",
  "RBF": "Radial Basis Function",
  "ReLU": "Rectified Linear Unit",
  "RMVCNN": "Recurrent Multi-View Convolutional Neural Network",
  "RF": "Random Forest",
  "SA": "Semantische Anreicherung",
  "SIA": "Schweizerischen Ingenieur- und Architektenverein",
  "SVM": "Support Vector Machine",
  "TFBB": "Objektausgerichtete Begrenzungsboxen",
  "XGBoost": "eXtreme Gradient Boosting",
  "XML": "Extensible Markup Language",
  "WandB": "Weights & Biases",
  "WBS": "Work Breakdown Structure",
))
