#import "/template/_helpers.typ": hint, title-caption, todo
#import "@preview/acrostiche:0.7.0": acr

= Ausgangslage, Problemstellung, Zielsetzung, Thesisorganisation <problem>

== Ausgangslage
Die Baubranche ist einer der grössten Wirtschaftssektoren weltweit. Ungefähr 7 % der weltweit erwerbstätigen Personen arbeiten in dieser Branche und es wird geschätzt, dass jährlich 10 Billionen US Dollar für Materialien und Dienstleistungen im Bauwesen ausgegeben werden @slusarczyk_machine_2024. Trotz der wirtschaftlichen Grösse stösst die Digitalisierung in der Baubranche auf grosse Herausforderungen. Neue Technologien werden nur langsam angewendet und weisen in ihrer Umsetzung oft eine hohe Komplexität auf @young_challenges_2021 @leviakangas_keeping_2017.

Die #acr("BIM")-Methode gewinnt im Bausektor zunehmend an Bedeutung und erstreckt sich über den gesamten Lebenszyklus eines Gebäudes @slusarczyk_machine_2024. Sie bildet die Grundlage für eine datengestützte Planung und ermöglicht Analysen sowie die Gewinnung von Projektwissen @zabin_applications_2022. Trotz der zunehmenden Verbreitung wird #acr("BIM") im Bausektor oft nur als Software zur Erstellung von 3D-Modellen genutzt @smith_bim_implementation_2014, obwohl eine feingranulare Klassifikation der Objekte für die Interoperabilität über den gesamten Lebenszyklus essenziell wäre @tang_automatic_2025.

Wie #cite(<pishdad_analysis_2024>, form: "prose") aufzeigt, hat #acr("BIM") das Potenzial, Kostenanalysen zu jeder Projektphase zu ermöglichen. Es zeigt sich zudem, dass die Nutzung eines standardisierten Kostenklassifikationssystems als #acr("BIM")-Methode die Projektkostentransparenz und die Visualisierung der Kostenentwicklung fördert und die Budgetkontrolle erleichtert @pishdad_analysis_2024. Des Weiteren ermöglicht die Verwendung von #acr("BIM") bei einer Projektänderungen eine rasche Aktualisierung der Projektkosten durch ein Modellupdate, was eine klare Effizienzsteigerung mit sich bringt @banihashemi_machine_2022.

Das Forschungsfeld #acr("KI") in #acr("BIM") wächst zwar in den letzten Jahren rasant @pan_integrating_2023, dennoch befinden sich praxisreife Applikationen noch in einer frühen Phase und beschränken sich häufig auf Konzepte oder kleinere Experimente @zabin_applications_2022.

== Problemstellung
Die Klassifikation von Bauelementen in #acr("IFC")-Modellen ist ein wichtiger Grundstein und von eminenter Bedeutung für eine erfolgreiche Umsetzung der #acr("BIM") Methode im Projektumfeld. Fehler in der Klassifikation führen zu erheblichen Problemen. In diesem Zusammenhang liegt die aktuelle Problematik darin, dass #acr("BIM") Autorensoftwaren oft nicht über die volle Bandbreite der benötigten Bauelemente verfügen, um eine ganzheitliche Modellierung eines Gebäudes zu gewährleisten @ma_3d_2018. Wie aus der Studie von #cite(<ma_3d_2018>, form: "prose") hervorgeht, improvisieren modellierende Personen daher oft und verschlechtern dabei die Modellqualität erheblich. Zudem werden beim Austausch unter den Projektbeteiligten #acr("IFC")-Modelle weitergegeben, welche durch den Export aus den nativen #acr("CAD") Softwaren oft nur als Referenzgeometrie verwendet werden. Dies führt zu einem Verlust von Klassifikationsinformationen @ma_3d_2018. Selbst wenn der #acr("IFC") Standard von allen bestehenden #acr("BIM") Softwareplattformen vollständig eingehalten wird, besitzen die #acr("CAD") Applikationen interne Klassifikationen, welche im #acr("IFC")-Schema nicht abgebildet sind und deshalb nicht exportiert werden können. Aus diesem Grund kann eine #acr("BIM") Interoperabilität nicht garantiert werden. Erschwerend kommt dazu, dass das #acr("IFC")-Schema eine grosse Flexibilität erlaubt, womit das Schema auf unterschiedliche Arten angewendet werden kann. Ein Beispiel dafür ist, dass eine Wand als #acr("IFC") Entität wie "IfcWall", "IfcSlab" oder auch "IfcBeam" klassifiziert werden kann @wu_automated_2018.

Wie aus der Studie von #cite(<wu_automated_2018>, form: "prose") zu entnehmen ist, sind die Entitäten und Attribute in einem #acr("IFC")-Schema grundsätzlich klar definiert. Dennoch wird Flexibilität der Objektkategorisierung durch folgende Gegebenheiten zugelassen:
1. Zulässigkeit von mehreren verschiedenen Möglichkeiten zur Darstellung eines Objekts
2. Möglichkeit der benutzerdefinierten Darstellung von Informationen unter Verwendung von #acr("IFC") #acr("Psets")
3. Potentielle Beeinflussung der Informationsdarstellung unter Verwendung von #acr("IFC") durch Modellierungsentscheidungen

Beim #acr("IFC")-Modellaustausch gehen zusätzlich implizite semantische Informationen verloren @wang_framework_2024, die moderne #acr("BIM")-Tools nicht zuverlässig rekonstruieren können @bloch_connecting_2022. Als Reaktion wird die semantische Anreicherung von #acr("IFC")-Modellen erforscht, um diese impliziten Informationen automatisch wieder herzustellen @belsky_semantic_2016.

Trotz den unterschiedlichen Vorteilen bei der Anwendung von #acr("BIM") Methoden werden bei Kostenschätzungen heutzutage oft die Ausmasse von ausgedruckten Plänen und 2D Dokumenten ermittelt. Dieser Prozess ist nicht nur fehleranfällig, sondern auch zeitaufwändig und stark abhängig vom Wissen der Fachpersonen. Anspruchsvolle und komplexe Bauprojekte erschweren diesen Prozess zusätzlich @monteiro_survey_2013 @liu_ontology-based_2016 @ma_formalized_2016 @banihashemi_data-centric_2022. Zudem fehlen Standards für eine Kostenklassifikation innerhalb der einzelnen Bauelemente. Weshalb das gesamte Vorgehen zusätzlich zeitaufwändig, fehleranfällig und mit einem niedrigen Return on Investment behaftet ist  @sompolgrunk_building_2021 @sompolgrunk_integrated_2022. Erste Bestrebungen in Richtung der Behebung der Problematik wurden von der #link("https://www.idc.ch")[IDC AG] unternommen, indem sie ein eigenes Mapping auf Basis des #acr("eBKP-H") erstellt haben, um die Kostenklassifikation von Bauelementen mit der #acr("BIM") Methode zu ermöglichen. Bauelemente müssen mit diesem Mapping manuell klassifiziert werden, was zu einem grossen Aufwand führt. Zwei Studien bestätigen, dass die Klassifikation von Bauelementen in der Praxis sehr arbeitsintensiv sowie zeitaufwändig ist und zu einer Kostensteigerung führt @petrochenko_machine_2024 @bloch_comparing_2018.

Weiterführend wurden regelbasierte Klassifikationen auf Basis von Fachwissen entwickelt, welche oft subjektiv und schwer zu standardisieren sind. Die Erstellung solcher Regeln ist zeitaufwändig und bei Änderungen müssen sie manuell angepasst werden @tang_automatic_2025. Ein weiteres Problem ist die fehlende Präzision und Mehrdeutigkeit der Regeln. Bauelemente, deren Merkmale nicht den definierten Annahmen entsprechen, können dadurch nicht korrekt klassifiziert werden @ma_3d_2018. Bei Ungewissheit werden Bauelemente in #acr("IFC")-Modellen als IfcBuildingElementProxy Entität klassifiziert. Dies bedeutet, dass es sich um ein beliebiges Bauteil handelt @ifcopenshell_2026. Solche Bauteile können nicht korrekt klassifiziert werden, da sie oft nicht den definierten Regeln entsprechen. Diese Vorgehen führt zu einem elementaren Informationsverlust @collins_shape_2022 @bloch_comparing_2018 @sacks_building_2020 @emunds_sparse-bim_2022.

Die Datenvorbereitung für #acr("KI")-Modelle ist in der Baubranche eine zentrale Herausforderung, da es an Leitlinien und etablierten Toolchains für die Umwandlung von #acr("IFC")-Dateien in nutzbare Formate fehlt. Gemäss #cite(<du_bim_2024>, form: "prose") befindet sich die Datenbereitschaft für #acr("KI") in der Branche entsprechend auf einem mittleren Niveau. Aus diesen Gründen weist die Baubranche noch viele Herausforderungen in der Interoperabilität auf. Zudem sind die geforderten #acr("BIM")-Informationen oft komplex, da sie Objektgeometrien und semantisches Wissen umfassen @wang_framework_2024.
#pagebreak()

== Zielsetzung
Basierend auf der Aufgabenstellung (@baa_task) der #link("https://www.gks.ch")[GKS Architekten AG] soll im Rahmen der Arbeit ein Modell entwickelt werden, welches in der Lage ist, Bauteile nach den benötigten Klassen für eine Zuweisung nach #acr("eBKP-H") als Qualitätssicherung zu prüfen. Diese Zielsetzung wurde zudem in einem ersten Interview (@first_interview_gks) mit dem Leiter der Baumanagement bei #link("https://www.gks.ch")[GKS Architekten AG] bekräftigt. Dabei ist die Performance der Modelle über die Inferenzzeit zu legen. Des Weiteren sollen die Vorhersagen des finalen Modells mit plausiblen Informationen rückgemeldet werden. Nur dadurch können Fachpersonen mit diesen Informationen in der Qualitätsprüfung der #acr("IFC")-Modelle unterstützt werden. Mit dieser Qualitätsprüfung wird der manuelle Klassifikationsprozess durch eine #acr("QS") gestärkt und Fehlerpotenziale werden minimiert.

Zur Klassifikation von relevanten Bauelementen für eine Zuweisung nach #acr("eBKP-H") gibt es zurzeit keine Literatur. Diese Arbeit legt damit einen ersten Grundstein für einen #acr("KI")-gestützten Qualitätssicherungsprozess. Verwandte Studien zur #acr("IFC")-Klassifikation zeigen bereits, dass mit geometrischen Features wie Bounding Box, Orientierung, Volumen und Zentroid sehr gute Resultate erzielt werden können @ma_3d_2018. Bei #acr("SVM") wird eine Accuracy von 94,4 % @koo_using_2019 und bei Ensemble-Methoden bis zu 95,0 % @li_ensemble-learning-based_2022 erreicht. Zudem konnten Modelle, welche lediglich auf geometrischen Features basieren, Accuracies zwischen 83,0 und 85,0 % erzielen @abualdenien_ensemble_learning_2022.

Auf Basis der vorher erwähnten Ausgangslage und der Aufgabenstellung der #link("https://www.gks.ch")[GKS Architekten AG] werden in dieser Arbeit folgende spezifische Hypothesen verfolgt:
- Geometrische Features aus #acr("IFC")-Modellen sind ausreichend, um relevante Labels zur Qualitätssicherung für ein eBKP-H Mapping mit einem Macro-F1 von ≥ 0,70 pro Label vorherzusagen.
- Gradient-Boosting-Verfahren (LightGBM, XGBoost) erreichen für die Multi-Output-Klassifikation der relevanten Labels vergleichbare Werte wie Random Forest bei deutlich kürzerer Trainingszeit auf identischer Hardware.

Durch das Erreichen dieser Hypothesen wird ein wichtiger Grundstein für die automatisierte Qualitätsprüfung bei #acr("BIM")-Modellen gelegt und ein Weg aufgezeigt, die Interoperabilität in der Baubranche zu stärken.

== Organisation der Thesis
Die vorliegende Arbeit ist in sieben Kapitel gegliedert. Das @problem behandelt die Ausgangslage, Problemstellung sowie die Zielformulierung. Im @research wird der aktuelle Stand der Forschung und der Praxis beschrieben, indem bisherige sowie verwandte Arbeiten zur Klassifikation von Bauelementen in #acr("IFC")-Modellen aufgezeigt werden. Das @methods beschreibt die verwendeten Methoden, das Vorgehensmodell sowie die Vorgehensweise zur Extraktion von Features und Modellentwicklung. Die Erläuterung zur Realisierung, Durchführung von Experimenten, Wahl diverser Ansätze und Entscheidungen erfolgen im @implementation. Das @evaluation präsentiert die Validierung und Evaluation der entwickelten Lösung hinsichtlich Qualität und Leistungsfähigkeit. Abschliessend reflektiert @outlook die eigene Arbeit, verweist auf ungelöste Probleme und zeigt Möglichkeiten für zukünftige Weiterentwicklungen auf.

Alle Abbildungen und Tabellen in dieser Thesis wurden eigenständig erstellt, sofern nicht anders angegeben. Relevante Dokumente und der Quellcode sind im zugehörigen #link("https://github.com/Valairaa/hslu_baa_ebkph_classifier")[Repository] #footnote("https://github.com/Valairaa/hslu_baa_ebkph_classifier") verfügbar. Der im Rahmen dieser Thesis erstellte, anonymisierte #link("https://www.kaggle.com/datasets/lukasstoeckli/geometric-features-for-ebkp-h-classification")[Datensatz] #footnote("https://www.kaggle.com/datasets/lukasstoeckli/geometric-features-for-ebkp-h-classification") mit den extrahierten geometrischen Features wurde zudem öffentlich auf Kaggle publiziert und ist frei zugänglich.
